[package]
name = "notblackrus/playeranimator"
description = "Take control of your player's replicated animations!"
version = "0.1.5"
license = "MIT"
authors = ["NotBlackrus"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/NotBlackrus/PlayerAnimator"
exclude = ["aftman.toml", "rokit.toml", "*.rbxl", "*.rbxm", "*.lua"]

[dependencies]
bytenet-max = "elitriare/bytenet-max@0.2.1"
Janitor = "howmanysmall/janitor@^1.17.0"
signalplus = "alexanderlindholt/signalplus@3.7.2"